### ISSUE TITLE
Add a table with properties to README

### ISSUE THREAD

**Issue by lukasz-gryzbon** [integreety/lsd-distributed-interceptor-library#30]
Follow the `lsd-core` example

**Comment by lukasz-gryzbon** [comment]
@nickmcdowall Please have a look if this is OK. Thanks

**Comment by nickmcdowall** [comment]
Hey 👋 

Nice one 😃 

Couple minor things I noticed:
* Spotted a small typo here: Capped database collection size `ion` megabytes.

* Maybe worth mentioning that the truststore related properties are optional and only required for TLS where the certificate if provided? (but maybe that's obvious anyway 🤷 )

Otherwise looking good! Nice one 👍

**Comment by lukasz-gryzbon** [comment]
Thanks @nickmcdowall!  Updated. Cheers.
